name: CustomItemAPI
description: CustomItemAPI

main: customiesdevs\customies\Customies
src-namespace-prefix: customiesdevs\customies
version: 4.0.0
api: 4.0.0

authors:
  - DenielWorld
  - TwistedAsylumMC
  - Refaltor # only for the CustomItemAPI
contributors:
  - JackNoordhuis
  - Unickorn
  - abimek
