---
items:

  test_basic_item:
    type: basic # basic | food | armor | tool
    name: test basic
    id: 1000
    meta: 0
    max_stack_size: 2
    texture_path: stick # texture present in the 'items/' folder

# template for armor item
  test_armor_item:
    type: armor
    name: test armor
    id: 1001
    meta: 0
    armor_group: helmet # helmet | chestplate | leggings | boots
    texture_path: stick
    max_durability: 100
    defense_points: 5

  test_food_item:
    type: food
    name: apple pen
    id: 1002
    meta: 0
    max_stack_size: 16
    texture_path: apple
    food_restore: 4
    saturation_restore: 20.00

# template for tool item
  test_pickaxe_item:
    type: tool
    name: test tool
    id: 1000
    meta: 0
    mining_efficiency: 10
    max_durability: 500
    tool_group: pickaxe # pickaxe | shovel | sword | axe | hoe
    texture_path: blaze_rod
    attack_points: 5 # required for sword
    tier: diamond # diamond | gold | iron | stone | wood
...
